#version: '3.8'

services:
  pickleball-shop:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: pickleball-shop:v1.0
    container_name: pickleball-shop
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      app:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - pickleball-shop
      - fluentbit
    networks:
      app:
    command: "nginx -g 'daemon off;'"

  fluentbit:
    image: fluent/fluent-bit:latest
    container_name: fluentbit
    volumes:
      - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./docker/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./nginx/logs:/var/log/nginx:ro
    depends_on:
      - splunk
    ports:
      - "24224:24224"
      - "2020:2020"
    command: -c /fluent-bit/etc/fluent-bit.conf
    networks:
      app:
        ipv4_address: 172.28.0.10

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"
      - "8088:8088"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=admin@123
    networks:
      - app
volumes:
  db_data:
  splunk_data:

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.0.0/24
